services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx-gateway
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - vsms-api
      
  vsms-api:
    build:
      context: .
      dockerfile: VSMS.Application/Dockerfile
    container_name: vsms-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - DOTNET_URLS=http://+:6000
      - IdentityServiceSettings__SecretKey=${IDENTITY_SERVICE_SECRET_KEY}
      - IdentityServiceSettings__Audience=${IDENTITY_SERVICE_AUDIENCE}
      - IdentityServiceSettings__Issuer=${IDENTITY_SERVICE_ISSUER}
      - IdentityServiceSettings__Url=${IDENTITY_SERVICE_URL}
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro
    expose:
        - "6000"
    ports:
      - "80:6000"
        
  identity-service:
    build:
      context: .
      dockerfile: VSMS.Identity.Application/Dockerfile
    container_name: identity-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${IDENTITY_SERVICE_ENVIRONMENT}
      - DOTNET_URLS=http://+:6010
      - ConnectionStrings__DefaultConnection=${IDENTITY_SERVICE_DEFAULT_DB_CONNECTION_STRING}
      - LokiSettings__Url=${IDENTITY_SERVICE_LOKI_URL}
      - LokiSettings__AppName=${IDENTITY_SERVICE_LOKI_APP_NAME}
      - JwtSettings__SecretKey=${IDENTITY_SERVICE_SECRET_KEY}
      - JwtSettings__Issuer=${IDENTITY_SERVICE_ISSUER}
      - JwtSettings__Audience=${IDENTITY_SERVICE_AUDIENCE}
      - JwtSettings__ExpiresInMinutes=${IDENTITY_SERVICE_JWT_EXPIRES}
    expose:
      - "6010"

  company-service:
    build:
      context: .
      dockerfile: VSMS.Company.Application/Dockerfile
    container_name: company-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${COMPANY_SERVICE_ENVIRONMENT}
      - DOTNET_URLS=http://+:6020
      - ConnectionStrings__DefaultConnection=${COMPANY_SERVICE_DEFAULT_DB_CONNECTION_STRING}
      - LokiSettings__Url=${COMPANY_SERVICE_LOKI_URL}
      - LokiSettings__AppName=${COMPANY_SERVICE_LOKI_APP_NAME}
    expose:
      - "6020"

  stock-service:
    build:
      context: .
      dockerfile: VSMS.Stock.Application/Dockerfile
    container_name: stock-service
    environment:
      - ASPNETCORE_ENVIRONMENT=${STOCK_SERVICE_ENVIRONMENT}
      - DOTNET_URLS=http://+:6030
      - ConnectionStrings__DefaultConnection=${STOCK_SERVICE_DEFAULT_DB_CONNECTION_STRING}
      - LokiSettings__Url=${STOCK_SERVICE_LOKI_URL}
      - LokiSettings__AppName=${STOCK_SERVICE_LOKI_APP_NAME}
    expose:
      - "6030"